### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by unfussygarlic** [unfussygarlic/SplendorDEL#1]
Display:
- [x]  Add requirement digits
- [ ]  Card background
- [ ]  Font correction
- [ ]  Text color assignment
- [x]  Player deck placement
- [x]  Show player score
- [ ]  Scalable dimensions
